name: Deploy docusaurus to github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies...!
        run: yarn install --frozen-lockfile
      - name: build things!
        run: yarn build
      - name: deploy to github pages! finally!
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
